### PR TITLE
Adds second verse

### PR DESCRIPTION
**Pull request by buaamer81**
Adds second verse of "'Love Yourself"

### CODE REVIEW

**Comment by buaamer81** [comment]
@tesfayesg Please review and merge to main if ok

**Comment by tesfayesg** [comment]
Hi , Rami
I was about to push and pull on Vs but I stuck for a reason which asks me
to debug about username in git mismatch
now I have another class at 5pm , if you can an idea about to help me on
solving see you after class 7pm
thanks
Selamawit

**Comment by Squarebanks** [comment]
@tesfayesg let's troubleshoot your issue. Can you respond on the slack chat where you are stuck and let us know your availability this week in case we need to jump on zoom? @VasquezNikolas let's keep the ball rolling. Would you mind reviewing this push request and committing?

**Comment by tesfayesg** [comment]
it looks good

**Comment by tesfayesg** [comment]
merge it

**Comment by VasquezNikolas** [comment]
looks Great :)

**Comment by VasquezNikolas** [comment]
Looks great :)

**Comment by tesfayesg** [comment]
add the text

**Pull request merged**
